-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.users
(
    usr_id serial NOT NULL,
    usr_name text NOT NULL,
    usr_email text NOT NULL UNIQUE,
    usr_password text NOT NULL,
    usr_type text NOT NULL DEFAULT 'user',
    usr_active boolean NOT NULL DEFAULT TRUE,
    PRIMARY KEY (usr_id)
);

CREATE TABLE IF NOT EXISTS public.street_arts
(
    sta_id serial NOT NULL,
	sta_usr_id serial NOT NULL,
    sta_artist text NOT NULL,
    sta_project text NOT NULL,
    sta_year integer NOT NULL,
    sta_photo_credits text NOT NULL,
    sta_address text NOT NULL,
    sta_coords point NOT NULL,
    sta_status text NOT NULL,
    sta_published boolean NOT NULL DEFAULT FALSE,
    sta_active boolean NOT NULL DEFAULT TRUE,
    PRIMARY KEY (sta_id)
);

CREATE TABLE IF NOT EXISTS public.images
(
    img_id serial NOT NULL,
    img_sta_id serial NOT NULL,
	img_usr_id serial NOT NULL,
	img_url text NOT NULL,
    img_published boolean NOT NULL DEFAULT FALSE,
    img_active boolean NOT NULL DEFAULT TRUE,
    PRIMARY KEY (img_id)
);

ALTER TABLE IF EXISTS public.images
    ADD FOREIGN KEY (img_sta_id)
    REFERENCES public.street_arts (sta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.images
    ADD FOREIGN KEY (img_usr_id)
    REFERENCES public.users (usr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.street_arts
    ADD FOREIGN KEY (sta_usr_id)
    REFERENCES public.users (usr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
